var players = [
    {
        nome: Hayley,
        HP: 100,
        anima:5,
        martial:10,
        handgun:25,
        bow:0,
        rifle:0,
        smg:0,
        shotgun:0,
        sniper:0,
        white:0,
        blunt:0,
        stealth:0,
        Carisma:0,
        strength:0,
        Agility:0,
        Dodge:20,
        insanity:7,
        dinheiro: ["", ""],
        items:["", ""],
    },
    {
        nome: Bill,
        HP: 90,
        anima:20,
        martial:8,
        handgun:1,
        bow:0,
        rifle:0,
        smg:0,
        shotgun:0,
        sniper:0,
        white:0,
        blunt:0,
        stealth:0,
        Carisma:19,
        strength:0,
        Agility:1,
        Dodge:15,
        insanity:31,
        dinheiro: ["", ""],
        items:["", ""],
    },
    {
        nome: Ortiz,
        HP: 100,
        anima:25,
        martial:0,
        handgun:5,
        bow:0,
        rifle:0,
        smg:0,
        shotgun:0,
        sniper:0,
        white:0,
        blunt:0,
        stealth:5,
        Carisma:15,
        strength:0,
        Agility:0,
        Dodge:0,
        insanity:29,
        dinheiro: ["", ""],
        items:["", ""],
    },
    {
        nome: Luca,
        HP: 110,
        anima:20,
        martial:0,
        handgun:0,
        bow:0,
        rifle:0,
        smg:0,
        shotgun:0,
        sniper:0,
        white:10,
        blunt:0,
        stealth:0,
        Carisma:20,
        strength:0,
        Agility:0,
        Dodge:0,
        insanity:7,
        dinheiro: ["", ""],
        items:["", ""],
    },
    {
        nome: Allen,
        HP: 125,
        anima:5,
        martial:8,
        handgun:6,
        bow:0,
        rifle:8,
        smg:3,
        shotgun:3,
        sniper:0,
        white:0,
        blunt:0,
        stealth:0,
        Carisma:0,
        strength:11,
        Agility:0,
        Dodge:0,
        insanity:"",
        dinheiro: ["", ""],
        items:["", ""],
    },
    {
        nome: Ricardo,
        HP: 100,
        anima:5,
        martial:0,
        handgun:0,
        bow:0,
        rifle:0,
        smg:0,
        shotgun:0,
        sniper:0,
        white:0,
        blunt:1,
        stealth:0,
        Carisma:20,
        strength:20,
        Agility:0,
        Dodge:5,
        insanity:9,
        dinheiro: ["", ""],
        items:["", ""],
    },
    {
        nome: Steve,
        HP: 110,
        anima:5,
        martial:10,
        handgun:10,
        bow:0,
        rifle:0,
        smg:0,
        shotgun:0,
        sniper:0,
        white:0,
        blunt:0,
        stealth:0,
        Carisma:13,
        strength:10,
        Agility:0,
        Dodge:5,
        insanity:5,
        dinheiro: ["", ""],
        items:["", ""],
    },
    {
        nome: Devin,
        HP: 105,
        anima:8,
        martial:0,
        handgun:0,
        bow:20,
        rifle:0,
        smg:0,
        shotgun:0,
        sniper:0,
        white:10,
        blunt:0,
        stealth:13,
        Carisma:10,
        strength:0,
        Agility:0,
        Dodge:0,
        insanity:18,
        dinheiro: ["", ""],
        items:["", ""],
    },
    {
        nome: Alison,
        HP: 105,
        anima:8,
        martial:10,
        handgun:9,
        bow:0,
        rifle:0,
        smg:0,
        shotgun:0,
        sniper:0,
        white:0,
        blunt:0,
        stealth:0,
        Carisma:10,
        strength:0,
        Agility:0,
        Dodge:10,
        insanity:0,
        dinheiro: ["", ""],
        items:["", ""],
    },
    {
        nome: Tsuki,
        HP: 109,
        anima0,
        martial:0,
        handgun:0,
        bow:0,
        rifle:0,
        smg:0,
        shotgun:0,
        sniper:0,
        white:10,
        blunt:0,
        stealth:10,
        Carisma:0,
        strength:0,
        Agility:10,
        Dodge:0,
        insanity:0,
        dinheiro: ["", ""],
        items:["", ""],
    }
]